//
// Created by Ola on 15.04.2024.
//

#ifndef TRAVELING_SALESMAN_PROBLEM_FILEREADER_H
#define TRAVELING_SALESMAN_PROBLEM_FILEREADER_H


class fileReader {

};


#endif //TRAVELING_SALESMAN_PROBLEM_FILEREADER_H
